name: CryptoSpark
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010522'
    - '#c5f1ff'
    - '#99bcc9'
    - '#425262'
    - '#698090'
  brandStrength: 0.5
  lightness: 0.8577964457217604
  saturation: 0.0064440814312547445
  rhythmicContrast: 0.5543276404496282
purpose: []
