name: CryptoSpark
favicon: null
layout_spectrum: 0.76113
typography_spectrum: 0.55204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000004'
    - '#cee9fa'
    - '#283c54'
    - '#3c678a'
    - '#7badd0'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
