name: CryptoSpark
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55204
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f7a20c'
    - '#f38a08'
    - '#ffeb83'
    - '#fcc856'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
