name: CryptoSpark
favicon: null
layout_spectrum: 0.76113
typography_spectrum: 0.55204
title: Cryptographic Wealth Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#b0b0b0'
    - '#ff0000'
    - '#00ff00'
  brandStrength: 1
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
